"""initial schema

Revision ID: 051d61f9a103
Revises: 
Create Date: 2026-08-02 16:48:01.852224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051d61f9a103'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('muscle_group', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_exercise_name'), 'exercises', ['exercise_name'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_is_custom'), 'exercises', ['is_custom'], unique=False)
    op.create_index(op.f('ix_exercises_muscle_group'), 'exercises', ['muscle_group'], unique=False)
    op.create_table('exercise_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('current_reps', sa.Integer(), nullable=False),
    sa.Column('current_sets', sa.Integer(), nullable=False),
    sa.Column('achieved_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id')
    )
    op.create_index(op.f('ix_exercise_profiles_exercise_id'), 'exercise_profiles', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_profiles_id'), 'exercise_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_profiles_user_id'), 'exercise_profiles', ['user_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exercise_profile_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rep', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_profile_id'], ['exercise_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_logs_exercise_profile_id'), 'exercise_logs', ['exercise_profile_id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_id'), 'exercise_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_logs_id'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_exercise_profile_id'), table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_exercise_profiles_user_id'), table_name='exercise_profiles')
    op.drop_index(op.f('ix_exercise_profiles_id'), table_name='exercise_profiles')
    op.drop_index(op.f('ix_exercise_profiles_exercise_id'), table_name='exercise_profiles')
    op.drop_table('exercise_profiles')
    op.drop_index(op.f('ix_exercises_muscle_group'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_custom'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
